# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

---

- name: Disable root login
  user:
    name: root
    password: '!!'

- name: Setup SmartOS cloud-init
  copy:
    src: 90_smartos.cfg
    dest: /etc/cloud/cloud.cfg.d/90_smartos.cfg
    owner: root
    group: root
    mode: 0644

- name: Triton sdcvmtools lib/smartdc
  copy:
    src: lib/smartdc
    dest: /lib
    owner: root
    group: root

- name: Triton sdcvmtools mdata-client
  copy:
    src: "{{ item }}"
    dest: /usr/sbin/
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - "usr/sbin/mdata-*"


#ln -s /usr/sbin/mdata-get /lib/smartdc/mdata-get
- name: Triton symlink mdata-get
  file:
    src: /usr/sbin/mdata-get
    dest: /lib/smartdc/mdata-get
    owner: root
    group: root
    state: link
    force: true

- name: setup motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: link /etc/motd to /etc/issue
  file:
    src: /etc/motd
    dest: /etc/issue
    owner: root
    group: root
    state: link
    force: true


- name: link /etc/motd to /etc/issue.net
  file:
    src: /etc/motd
    dest: /etc/issue.net
    owner: root
    group: root
    state: link
    force: true

- name: fstrim cron job
  copy:
    src: fstrim.cron.sh
    dest: /etc/cron.daily/fstrim
    owner: root
    group: root
    mode: 0644